name: Publish to Release Files

on:
  release:
    types:
    - published 


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FILE_NAME: MotorTownDiscordBot.${{ github.ref_name}}.zip

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --no-self-contained
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Zip files
      working-directory: artifacts/publish/MotorTownDiscordBot/release_win-x64
      run:  zip -r "${{ runner.temp }}/$FILE_NAME" .
    - name: Create Release
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload --clobber "${{ github.ref_name}}" "${{ runner.temp }}/$FILE_NAME"
    
